name    'puppet-galera'
version '0.0.1'
source 'none'
author 'Michael Chapman'
license 'Apache License, Version 2.0'
summary 'Install/configure MySQL with Galera'
description 'Install/configure MySQL with Galera'
project_page 'https://github.com/michaeltchapman/puppet-galera'

# Dependencies
dependency 'puppetlabs/stdlib',  '>= 4.1.0'
dependency 'puppetlabs/apt',     '>= 1.4.1'
dependency 'puppetlabs/mysql',   '>=2.2.0'
dependency 'puppetlabs/firewall', '>=1.0.0'
dependency 'puppetlabs/xinetd',   '>=1.2.0'
